### ISSUE TITLE
Remove dependency on node-sass

### ISSUE THREAD

**Issue by djensen47** [sintaxi/terraform#87]
node-sass has been notoriously unstable due to it's dependency on libsass. In particular, it has never really worked on SmartOS/Solaris. PRs have been submitted but the fixes have never made it to the production version of node-sass. It's very frustrating.

Would it be possible to make it an optional dependency? That way, when you try to install on an unsupported libsass platform, you can still use harp? Or possibly use the slower Sass.js?

**Comment by kennethormandy** [comment]
Hey,

Thanks for opening an issue. Personally I wouldn’t characterise Node-sass or Libsass that way at all, in a relatively short period of time they’ve gone from a rough but workable implementation to something of a driving force in the Sass community. We bet on the Node-sass/Libsass combo fairly early and I think it’s proven to be the right choice. I’m not sure which Sass.js you’re referring to, but imposing Ruby as a dependency was less appealing to us than any of the other potential shortcomings.

Ideally, in the case of SmartOS where should compile on other platforms. If that’s not the case, we can help make some noise on specific issues if you want? We’ve done that in the past and they took the concerns seriously.

If you’re having problems with Harp specifically, it’s possible that it’s because we’re not running the latest version, so that would be on us. We will definitely ship a release of [Terraform](https://github.com/sintaxi/terraform) once Node-sass v3.0.0 stable is out. Otherwise, you might be able to use npm shrinkwrap to change out or bump Node-sass manually.

Hope that’s helpful :)

**Comment by djensen47** [comment]
I reviewed the past issues and didn't see other SmartOS problems. Sorry, maybe I was thinking of something else.

As it stands harp is 100% broken/unusable on SmartOS due to this issue. If you can make some noise for a fix in node-sass 2.x, that would be great.

**Comment by kennethormandy** [comment]
Sorry if that was brash. It looks like I misunderstood how the fallbacks worked in Node-sass and the binary building is in the Node-sass v3.0.0 alpha. You should be able to opt-into it manually using npm shrinkwrap or it will be in a new release of Terraform once it’s out of alpha.

**Comment by djensen47** [comment]
You weren't brash, I was the brash one – sorry about that.

Okay, I'll try again later. For now, checking in the compiled html and CSS
will make do.
